// Providers
export const DATABASE_CONNECTION = "DATABASE_CONNECTION";
export const PRODUCT_MODEL = "PRODUCT_MODEL";
export const CATEGORY_MODEL = "CATEGORY_MODEL";
export const ORDER_MODEL = "ORDER_MODEL";
